name: Build Windows CLI

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows-cli:
    name: Build for Windows x86_64
    runs-on: windows-latest  # 使用 Windows 构建环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable  # 使用稳定版 Rust
          target: x86_64-pc-windows-msvc  # Windows 目标平台

      - name: Build release binary
        run: |
          cargo build --release --manifest-path lib/rvemu-cli/Cargo.toml
          # 复制二进制文件到根目录便于归档
          cp lib/rvemu-cli/target/release/rvemu-cli.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rvemu-cli-windows
          path: rvemu-cli.exe